name: "Cloud Buildpack Build"

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Argonaut
    environment: tropical-test-e2e
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2
      - name: Get Short SHA
        id: get_sha
        run: echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)
      - name: Cat
        run: cat ./.art/art.yaml
      - name: Download art
        run: curl https://github.com/argonautdev/charts/releases/download/v0.2.0/art -L -o art
      - name: Configure art and Deploy app
        run: |
          chmod +x ./art
          sudo mv ./art /usr/local/bin/art
          art configure --key {{ secrets.ART_KEY }} --secret {{ secrets.ART_SECRET }}
          cat ~/.argonaut/config.yaml
          art app deploy -f ./.art/art.yaml --set image="registry.hub.docker.com/sayantank/test-e2e" --set imageTag="06aa88e"
