name: "Build and Push to CR"

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Img
    environment: tropical-test-baship
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: echo path
        run: echo ./.art/art.yaml
      - name: Fetch repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github container repo
        uses: docker/login-action@v1
        with:
          registry: registry.hub.docker.com/sayantank
          username: sayantank
          password: ${{ secrets.ARG_CR_ACCESS_TOKEN }}
      - name: Build Image and Push
        uses: docker/build-push-action@v2
        id: build-push
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.hub.docker.com/sayantank/test-baship:$(git rev-parse --short HEAD) , registry.hub.docker.com/sayantank/test-baship:${{ steps.get_version.outputs.VERSION }}