name: "Build and Push to CR"

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Img
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Fetch repo
        uses: actions/checkout@v2
      - name: Get Short SHA
        id: get_sha
        run: echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github container repo
        uses: docker/login-action@v1
        with:
          registry: registry.hub.docker.com
          username: sayantank
          password: ${{ secrets.ARG_skdocker_ACCESS_TOKEN }}
      - name: Build Image and Push
        uses: docker/build-push-action@v2
        id: build-push
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.hub.docker.com/sayantank/testing-dockerfile:${{ steps.get_sha.outputs.SHA_SHORT }}
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Argonaut
    needs: build
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2
      - name: Get Short SHA
        id: get_sha
        run: echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)
      - name: Download art
        run: curl https://github.com/argonautdev/charts/releases/download/v0.2.0/art -L -o art
      - name: Configure art
        run: |
          chmod +x ./art
          sudo mv ./art /usr/local/bin/art
          art configure --key ${{ secrets.ART_KEY }} --secret ${{ secrets.ART_SECRET }}
          art app deploy -f ./.art/art.yaml --set image="registry.hub.docker.com/sayantank/testing-dockerfile" --set imageTag="${{ steps.get_sha.outputs.SHA_SHORT }}" --set appName="testing-dockerfile"  --set argonaut.env="production" --set argonaut.region="us-east-2" --set argonaut.cluster="production" --set argonaut.imageRegistry="skdocker"